[package]
name = "hello"
authors = ["Mateus Leitao <mateuselpidio0@gmail.com>"]
version = "2.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
